config/routes.rb
Rails.application.routes.draw do
  get "/", to: "welcome#index"

  get "/shelters", to: "shelters#index"
  get "/shelters/new", to: "shelters#new"
  post "/shelters", to: "shelters#add"
  get "/shelters/:id", to: "shelters#show"
  get "/shelters/:id/edit", to: "shelters#edit"
  patch "/shelters/:id", to: "shelters#update"
  delete "/shelters/:shelter_id/pets/:pet_id", to: "shelter_pets#destroy"
  delete "/shelters/:id", to: "shelters#destroy"

  get "/pets/:id", to: "pets#show"
  get "/pets", to: "pets#index"
  get "/shelters/:shelter_id/pets", to: "shelter_pets#index"
  get "/shelters/:shelter_id/pets/new", to: "pets#new"
  post "/shelters/:shelter_id/pets", to: "pets#create"
  get "/pets/:pet_id/edit", to: "pets#edit"
  patch "/pets/:pet_id", to: "pets#update"
  delete "/pets/:id", to: "pets#destroy"

  patch "/pets/:pet_id/pending", to: "pets#adoption_status_pending"
  patch "/pets/:pet_id/adoptable", to: "pets#adoption_status_adoptable"

  get "shelters/:shelter_id/reviews/new", to: "reviews#new"
  post "shelters/:shelter_id/reviews", to: "reviews#create"
  get "/shelters/:shelter_id/reviews/:review_id/edit", to: "reviews#edit"
  patch "/shelters/:shelter_id/reviews/:review_id", to: "reviews#update"
  delete "/shelters/:shelter_id/reviews/:review_id", to: "reviews#destroy"

  get "/favorites", to: "favorites#index"
  patch "/favorites/:pet_id", to: "favorites#update"
  delete "/favorites/:pet_id", to: "favorites#remove"
  delete "/favorites", to: "favorites#destroy"

  get "/applications/new", to: "applications#new"
  get "/applications/:application_id", to: "applications#show"
  get "/pets/:pet_id/applications", to: "pet_applications#index"
  post "/applications", to: "applications#create"

  resources :pet_applications, only: [:update, :destroy]
end

app/models/application.rb
class Application < ApplicationRecord
  validates_presence_of :name, :address, :city, :state, :zip, :phone_number, :description
  has_many :pet_applications
  has_many :pets, through: :pet_applications

  def self.applications_by_pet(params)
    Pet.find(params[:pet_id]).applications
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :favorites

  def favorites
    @favorites ||= Favorite.new(session[:favorites])
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController

  def new
  end

  def create
    application = Application.new(application_params)
    if application.save
      favorites.pets_applied(application, params)
      flash[:notice] = "Your application for #{pets_applied_for} has been submitted."
      redirect_to "/favorites"
    else
      flash[:notice] = "Unable to create application: #{application.errors.full_messages.to_sentence}."
      render :new
    end
  end

  def show
    @application = Application.find(params[:application_id])
  end

  private

  def application_params
    params.permit(:name, :address, :city, :state, :zip, :phone_number, :description)
  end

  def pets_applied_for
    pets = []
    params.each do |key, value|
      if value == "applied"
        pets << Pet.find(key).name
      end
    end
    pets.to_sentence
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applications/index.html.erb
<h2>All Applications</h2>

<section class="list-of-applicants">
  <% @applications.each do |application| %>
    <section id="application-<%= application.id %>">
    <%= link_to application.name, "/applications/#{application.id}" %>
  <% end %>
</section>
<%= link_to "Go Back", :back %>

app/views/applications/new.html.erb
<h2>New Application</h2>

<%= form_tag "/applications", method: "post" do %>
  <% favorites.all_favorited_pets.each do |pet| %>
    <%= label_tag pet["name"] %><%= check_box_tag pet["id"], value = "applied" %><br>
  <% end %><br>
  <%= label_tag :name %>
  <%= text_field_tag :name %><br>
  <%= label_tag :address %>
  <%= text_field_tag :address %><br>
  <%= label_tag :city %>
  <%= text_field_tag :city %><br>
  <%= label_tag :state %>
  <%= text_field_tag :state %><br>
  <%= label_tag :zip %>
  <%= text_field_tag :zip %><br>
  <%= label_tag :phone_number %>
  <%= text_field_tag :phone_number %><br>
  <%= label_tag :description %>
  <%= text_area_tag :description %><br>
  <%= submit_tag "Submit Application" %>
<% end %>

<br><h5><%= link_to "Go Back", :back %></h5>

app/views/applications/show.html.erb
<h2><%= @application.name %>'s Application </h2>
<section class="applicant_info">
  <li>Name: <%= @application.name %></li>
  <li>Address: <%= @application.address %></li>
  <li>City: <%= @application.city %></li>
  <li>State: <%= @application.state %></li>
  <li>Zip: <%= @application.zip %></li>
  <li>Phone Number: <%= @application.phone_number %></li>
  <li>Description: <%= @application.description %></li><br>
  <li>Pets Applied for: </li><% @application.pets.each do |pet| %>
    <section id="pet_application_<%= pet.id %>">
      <%= link_to pet.name, "/pets/#{pet.id}" %> -
      <% if pet.approved_pet_app?(@application, pet) %>
        <%= link_to "Unapprove Application", pet_application_path(pet, app_id: @application), method: :delete, class: "box-links"%><br>
      <% else  %>
        <%= link_to "Approve Application", pet_application_path(pet, app_id: @application), method: :patch, class: "box-links"%><br>
      <% end %>
    </section>
  <% end %>
</section>
<%= link_to "Go Back", :back %>